import { expect, test, type Page, type Route } from "@playwright/test";

/**
 * G14 browser proof: the canonical V197 Projects adjunct is wired to the real
 * file + execution APIs. Upload stores real bytes (shown as a downloadable
 * deliverable), the Generate-evidence-package control drives the approval-gated
 * run, and Download retrieves the generated bytes. Backed by a faithful,
 * stateful mock of the backend contract; the real backend path is proven by the
 * API test suite and the live Celery worker smoke.
 */

const PROJECT_ID = "proj-g14";
const RUN_ID = "run-g14";
const now = new Date().toISOString();

const orbit = { id: "orbit-g14", title: "Deliverable Orbit", kind: "PROJECT" };
const user = {
  id: "owner-g14",
  email: "owner@nur.app",
  chosen_name: "Deliverable Owner",
  profile: { chosen_name: "Deliverable Owner", locale: "en" },
};

async function json(route: Route, body: unknown, status = 200) {
  await route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) });
}

function makeFile(overrides: Record<string, unknown>): Record<string, unknown> {
  return {
    id: `file-${Math.random().toString(36).slice(2, 10)}`,
    owner_user_id: user.id,
    project_id: PROJECT_ID,
    task_id: null,
    run_id: null,
    artifact_id: null,
    original_filename: "file.txt",
    safe_filename: "file.txt",
    media_type: "text/plain",
    byte_size: 12,
    checksum_sha256: "a".repeat(64),
    storage_state: "STORED",
    quarantine_reason: null,
    scan_state: "SCAN_NOT_CONNECTED",
    provenance: "OWNER_UPLOAD",
    created_at: now,
    updated_at: now,
    ...overrides,
  };
}

async function installBoot(page: Page) {
  await page.context().addCookies([{
    name: "nur_csrf", value: "g14-deliverables-csrf",
    url: "http://localhost:4173", httpOnly: false, sameSite: "Lax",
  }]);
  await page.route("**/api/v1/auth/me", route => json(route, user));
  await page.route("**/api/v1/profile/preferences", route => json(route, {
    locale: "en", sound_enabled: false, reduced_effects: true,
    default_boundary: "PRIVATE_ORBIT", active_orbit_id: orbit.id,
    omega_enabled: true, writing_preference: "default", timezone: "UTC",
  }));
  await page.route("**/healthz", route => json(route, { status: "ok" }));
  for (const path of [
    "**/api/v1/universe/live", "**/api/v1/universe/map-summary",
    "**/api/v1/universe/orbits-summary", "**/api/v1/universe/timeline",
    "**/api/v1/universe/insights-summary", "**/api/v1/map",
    "**/api/v1/glow/scoreboard",
  ]) await page.route(path, route => json(route, null));
  await page.route("**/api/v1/glow/summary", route => json(route, {
    balance: 0, lifetime_points: 0, today_points: 0, weekly_points: 0, level: 1,
    rank: "Orbit Seed", next_unlock: null, recent_transactions: [], streaks: [],
    achievements: [], daily_quest: {}, weekly_mission: {},
  }));
  await page.route("**/api/v1/research/briefs", route => json(route, []));
  await page.route("**/api/v1/community/rooms", route => json(route, []));
  await page.route("**/api/v1/orbits/current-state", route => json(route, {
    active_systems: 1, outcomes_returned: 0, insights_evolving: 0, open_questions: 0,
    research_staged: 0, plans_active: 0, live_status: "owner_ledger",
  }));
  await page.route("**/api/v1/orbits", route => json(route, [orbit]));
  await page.route("**/api/v1/journal", route => json(route, []));
  await page.route("**/api/v1/plans", route => json(route, []));
  await page.route("**/api/v1/cognition/talk-thread**", route => json(route, []));
}

async function installProjectMocks(page: Page) {
  const state: { files: Array<Record<string, unknown>>; run: Record<string, unknown> | null } = {
    files: [],
    run: null,
  };
  const project = {
    id: PROJECT_ID, owner_user_id: user.id, orbit_id: orbit.id,
    title: "Deliverable project", objective: "Package verifiable evidence.",
    status: "ACTIVE", system_slug: "creation", deadline: null, budget_cents: 1000,
    permission_policy: { external_actions_require_owner_approval: true },
    created_at: now, updated_at: now,
  };
  const task = {
    id: "task-g14", owner_user_id: user.id, project_id: PROJECT_ID, parent_task_id: null,
    title: "Assemble the package", description: null, acceptance_criteria: "Archive exists.",
    status: "READY", priority: 50, assigned_role: "implementer", due_at: null,
    completed_at: null, created_at: now, updated_at: now,
  };

  // Single dispatcher for the whole /projects surface (last-registered wins).
  await page.route(/\/api\/v1\/projects(\/|$|\?)/, async route => {
    const method = route.request().method();
    const path = new URL(route.request().url()).pathname.replace("/api/v1", "");
    // Writes first, so a POST upload is never swallowed by the GET list handler.
    if (path.endsWith("/files") && method === "POST") {
      const stored = makeFile({ original_filename: "source.txt", safe_filename: "source.txt", byte_size: 42 });
      state.files.push(stored);
      return json(route, stored, 201);
    }
    if (path === "/projects/summary") return json(route, null);
    if (path === `/projects/${PROJECT_ID}` && method === "GET") return json(route, project);
    if (path === `/projects/${PROJECT_ID}/tasks` && method === "GET") return json(route, [task]);
    if (path === `/projects/${PROJECT_ID}/evidence` && method === "GET") return json(route, []);
    if (path === `/projects/${PROJECT_ID}/reviews` && method === "GET") return json(route, []);
    if (path === `/projects/${PROJECT_ID}/artifacts` && method === "GET") return json(route, []);
    if (path === `/projects/${PROJECT_ID}/runs` && method === "GET") return json(route, state.run ? [state.run] : []);
    if (path === `/projects/${PROJECT_ID}/files` && method === "GET") return json(route, state.files);
    if (path === `/projects/${PROJECT_ID}/runs` && method === "POST") {
      state.run = {
        id: RUN_ID, owner_user_id: user.id, project_id: PROJECT_ID, task_id: task.id,
        role: "verifier", request_summary: "Generate a deterministic evidence package.",
        status: "PROPOSED", tool_policy: {}, budget_cents: 0, approval_required: true,
        approved_at: null, started_at: null, completed_at: null, result_summary: null,
        adapter_key: "EVIDENCE_PACKAGE", agent_id: null,
        requested_capabilities: ["artifact.write"], approved_capabilities: [],
        input_refs: {}, idempotency_key: null, timeout_seconds: null, cost_cents: 0,
        attempt: 0, worker_id: null, failure_code: null, output_artifact_id: null,
        queued_at: null, failed_at: null, cancelled_at: null, created_at: now, updated_at: now,
      };
      return json(route, state.run, 201);
    }
    if (path === `/projects/runs/${RUN_ID}/approve` && method === "POST") {
      state.run = { ...state.run!, status: "APPROVED", approved_at: now };
      return json(route, state.run);
    }
    if (path === `/projects/runs/${RUN_ID}/queue` && method === "POST") {
      // Inline-style success: a generated package appears as a RUN_OUTPUT file.
      state.run = { ...state.run!, status: "SUCCEEDED", output_artifact_id: "artifact-g14", worker_id: "inline" };
      state.files.push(makeFile({
        original_filename: "evidence-package.zip", safe_filename: "evidence-package.zip",
        media_type: "application/zip", byte_size: 1381, provenance: "RUN_OUTPUT",
        run_id: RUN_ID, artifact_id: "artifact-g14",
        checksum_sha256: "b".repeat(64),
      }));
      return json(route, state.run);
    }
    if (path === `/projects/runs/${RUN_ID}` && method === "GET") return json(route, state.run);
    if (path.endsWith("/download") && method === "GET") {
      return route.fulfill({
        status: 200,
        headers: {
          "content-type": "application/octet-stream",
          "content-disposition": 'attachment; filename="evidence-package.zip"',
          "x-content-type-options": "nosniff",
        },
        body: Buffer.from("PK nur evidence package bytes"),
      });
    }
    return json(route, []);
  });
}

for (const projectName of ["chromium-desktop", "chromium-mobile"]) {
  test(`[${projectName}] V197 Projects deliverables wire real upload, execution and download`, async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== projectName, "one device per iteration");
    await installBoot(page);
    await installProjectMocks(page);

    await page.goto(`/projects/${PROJECT_ID}/deliverables`);
    const universe = page.frameLocator("#nur-universe-stage");
    const root = universe.locator("#nur-v197-adjunct-root");
    await expect(root).toContainText("Deliverable project");
    const panel = root.locator('[data-adjunct-panel="deliverables"]');
    await expect(panel).toContainText("Deliverables");
    await expect(panel).toContainText("No stored bytes yet");

    // Upload a real file → it appears as a stored, downloadable deliverable.
    await panel.locator('input[type="file"]').setInputFiles({
      name: "source.txt", mimeType: "text/plain", buffer: Buffer.from("real source bytes\n".repeat(3)),
    });
    await panel.locator('[data-adjunct-action="project-file-upload"]').click();
    await expect(root.locator('[data-adjunct-list="project-files"]')).toContainText("source.txt");
    await expect(root.locator('[data-adjunct-list="project-files"]')).toContainText("OWNER_UPLOAD · STORED");

    // Generate an evidence package → the approval-gated run produces a deliverable.
    await root.locator('[data-adjunct-action="project-run-evidence-package"]').click();
    await expect(root.locator('[data-adjunct-list="project-files"]')).toContainText("evidence-package.zip", { timeout: 15_000 });
    await expect(root.locator('[data-adjunct-list="project-files"]')).toContainText("RUN_OUTPUT · STORED");

    // Download the generated package → a real browser download of the bytes.
    const downloadButtons = root.locator('[data-adjunct-action^="project-file-download-"]');
    await expect(downloadButtons.first()).toBeVisible();
    const [download] = await Promise.all([
      page.waitForEvent("download"),
      downloadButtons.last().click(),
    ]);
    expect(download.suggestedFilename()).toContain(".zip");
  });
}
